export interface BaseTable {
  id: number;
  number: string;
  capacity: string;
  status: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED' | 'MAINTENANCE';
  currentGuests: number;
  location: 'INDOOR' | 'OUTDOOR';
  lastCleaned: string;
  reservedBy: string | null;
  reservedTime: string | null;
  createdAt: string;
  updatedAt: string;
  createdById: string;
}

export interface CreateTableInput {
  number: string;
  capacity: string;
  location: 'INDOOR' | 'OUTDOOR';
}

// status default to 'available'
// reservedBy and reservedTime default to null
// id will be generated by the backend
//   lastCleaned will be a date string in ISO format and default date now in backend
//  currentGuests default to 0 in backend
