// const allOrders = [
//   // Hari ini
//   {
//     id: 'ORD-342',
//     customer: 'Budi Santoso',
//     items: 3,
//     total: 85000,
//     status: 'Selesai',
//     time: '14:30',
//     cashier: 'Maria',
//     date: new Date(),
//   },
//   {
//     id: 'ORD-341',
//     customer: 'Siti Rahayu',
//     items: 2,
//     total: 60000,
//     status: 'Sedang Dibuat',
//     time: '14:15',
//     cashier: 'Ahmad',
//     date: new Date(),
//   },
//   {
//     id: 'ORD-340',
//     customer: 'Ahmad Fauzi',
//     items: 1,
//     total: 35000,
//     status: 'Selesai',
//     time: '14:00',
//     cashier: 'Maria',
//     date: new Date(),
//   },
//   // Kemarin
//   {
//     id: 'ORD-339',
//     customer: 'Rina Wati',
//     items: 4,
//     total: 120000,
//     status: 'Selesai',
//     time: '16:45',
//     cashier: 'Ahmad',
//     date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
//   },
//   {
//     id: 'ORD-338',
//     customer: 'Joko Susanto',
//     items: 2,
//     total: 75000,
//     status: 'Selesai',
//     time: '15:20',
//     cashier: 'Maria',
//     date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
//   },
//   // 3 hari lalu
//   {
//     id: 'ORD-337',
//     customer: 'Dewi Sari',
//     items: 5,
//     total: 150000,
//     status: 'Selesai',
//     time: '13:10',
//     cashier: 'Ahmad',
//     date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
//   },
//   {
//     id: 'ORD-336',
//     customer: 'Bambang Wijaya',
//     items: 1,
//     total: 25000,
//     status: 'Selesai',
//     time: '12:30',
//     cashier: 'Maria',
//     date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
//   },
//   // 1 minggu lalu
//   {
//     id: 'ORD-335',
//     customer: 'Indah Permata',
//     items: 3,
//     total: 95000,
//     status: 'Selesai',
//     time: '11:15',
//     cashier: 'Ahmad',
//     date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
//   },
//   {
//     id: 'ORD-334',
//     customer: 'Agus Pratama',
//     items: 2,
//     total: 65000,
//     status: 'Selesai',
//     time: '10:45',
//     cashier: 'Maria',
//     date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
//   },
//   // 2 minggu lalu
//   {
//     id: 'ORD-333',
//     customer: 'Lisa Maharani',
//     items: 4,
//     total: 110000,
//     status: 'Selesai',
//     time: '16:20',
//     cashier: 'Ahmad',
//     date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
//   },
//   // 3 minggu lalu
//   {
//     id: 'ORD-332',
//     customer: 'Doni Setiawan',
//     items: 1,
//     total: 45000,
//     status: 'Selesai',
//     time: '14:55',
//     cashier: 'Maria',
//     date: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
//   },
//   // 1 bulan lalu
//   {
//     id: 'ORD-331',
//     customer: 'Fitri Handayani',
//     items: 6,
//     total: 180000,
//     status: 'Selesai',
//     time: '13:40',
//     cashier: 'Ahmad',
//     date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
//   },
// ];
